import uuid
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime

from sqlalchemy import select

from backend.models.goal import Goal
from backend.models.onboarding_question import OnboardingQuestion
from backend.repositories.base import BaseRepository

# What `onboarding_questions.ai_model` holds for a row no model wrote: the
# standard questions, and the "What do you want to learn?" row that carries the
# student's own words. Gemini-written rows carry the model that wrote them, so
# one read of a student's onboarding tells the two apart (#132).
SYSTEM_AUTHOR = "system"

# The free-text row's question: what the start screen asks before any
# multiple-choice question exists. It is the student's own words, so no option
# was selected and `selected_option_index` stays NULL.
PROMPT_QUESTION = "What do you want to learn?"

# What `ai_model` holds for a generated question whose answer came back without
# the model that wrote it - an app built before #216 kept none. Written as such
# rather than guessed: the question was generated by another request, and the
# model configured now need not be the one configured then.
UNKNOWN_AUTHOR = "unknown"


@dataclass(frozen=True)
class StandardAnswer:
    """One answered standard question, as the table stores it: the English
    question, its four options and the index of the one picked.

    Which question a key names is not this file's business (#211): the keys are
    resolved in `services/onboarding/standard_answers.py`, and this is what
    comes out of it.
    """

    question: str
    options: tuple[str, str, str, str]
    picked: int
    seconds: int | None


class OnboardingRepository(BaseRepository[OnboardingQuestion]):
    """Where the onboarding waits until the chain turns it into a context (#88).

    The chain has to be able to *read* the onboarding, not be handed it: goal
    creation writes these rows and returns, and whichever run of the chain gets
    there first - the one goal creation fires, or tomorrow night's after that
    one failed - reads them. An input that is only an argument is lost the
    moment the call that carried it fails.

    **What the table holds and what the API sends.** `onboarding_questions` has
    four option columns; `POST /goals` sends only the option the student picked
    (`ObjectiveAnswer` in schemas/goal.py deliberately omits the rest). So a row
    records the chosen text in `option_a` with `selected_option_index = 0`, and
    leaves the three options it was never told about empty. Widening the request
    to carry all four is a frontend change and buys the prompt nothing: what the
    student did *not* pick says little about them.

    The **standard questions** (#132) are the one kind of row that does know all
    four: they are written by us, not generated, so the row carries every option
    and the true index of the one picked. `answer_of` is the single rule that
    reads any of the three shapes back, so nothing outside this file has to know
    which shape a row is in.

    **Who wrote the question** is `ai_model`: the Gemini model for the ones it
    generated, as `POST /goals/objective-questions` named it and the app sent it
    back with the answer (`UNKNOWN_AUTHOR` when it did not); the literal
    `"system"` for the standard four and for the row holding the student's own
    words.

    **How long he took** is `total_seconds`, on every answered row of both
    kinds, as the app measured it; NULL when it sent none, and on the free-text
    row, which it does not time (#174).

    This is a *use* of a table that was created on every boot and read by nobody
    (#112). The schema changes since are `ai_model` (#132) and `total_seconds`
    (#174).
    """

    model = OnboardingQuestion

    async def save_onboarding(
        self,
        goal_id: uuid.UUID,
        prompt: str,
        answers: Sequence[tuple[str, str, int | None, str | None]],
    ) -> list[OnboardingQuestion]:
        """Persist one goal's onboarding: the student's own words first, then
        one row per question they answered, as `(question, answer, seconds,
        model)`.

        `model` wrote that question, None when nobody said which; the prompt row
        is ours, so it is `"system"` whatever the rest were written by.
        """
        rows = [self._row(goal_id, PROMPT_QUESTION, prompt, None, SYSTEM_AUTHOR, None)]
        rows += [
            self._row(goal_id, question, answer, 0, model or UNKNOWN_AUTHOR, seconds)
            for question, answer, seconds, model in answers
        ]
        self.db.add_all(rows)
        await self.db.flush()
        return rows

    async def save_standard_answers(
        self, goal_id: uuid.UUID, answers: list[StandardAnswer]
    ) -> list[OnboardingQuestion]:
        """Persist the answers to the standard questions: all four options and
        the one picked, marked as written by nobody (`SYSTEM_AUTHOR`)."""
        rows = [_standard_row(goal_id, answer) for answer in answers]
        self.db.add_all(rows)
        await self.db.flush()
        return rows

    async def list_by_student(
        self, student_id: uuid.UUID, as_of: datetime | None = None
    ) -> list[OnboardingQuestion]:
        """Everything the student told us while creating any of their goals,
        oldest first. A context is written about the person (#87), so it reads
        every goal's onboarding, not one goal's.

        `as_of` reads the onboarding *as it stood* at that moment. Goal creation
        passes the instant it wrote its rows, so the batch it fires cannot see
        the standard questions the student is answering while it runs (#132);
        every later run passes nothing and sees all of them.
        """
        stmt = (
            select(OnboardingQuestion)
            .join(Goal, Goal.id == OnboardingQuestion.goal_id)
            .where(Goal.student_id == student_id)
            .order_by(OnboardingQuestion.created_at.asc())
        )
        if as_of is not None:
            stmt = stmt.where(OnboardingQuestion.created_at <= as_of)
        result = await self.db.execute(stmt)
        return list(result.scalars().all())

    async def prompt_of(self, goal_id: uuid.UUID) -> str | None:
        """What the student typed for this goal, in his own words - the
        free-text row. None for a goal created without an onboarding.

        The goal's own name and description are Gemini's study plan, and they
        can be narrower than what he asked for ("understand modern China"
        became "digital China and business", 2026-09-26); this is the one
        record of what he actually said.
        """
        stmt = select(OnboardingQuestion.option_a).where(
            OnboardingQuestion.goal_id == goal_id,
            OnboardingQuestion.question == PROMPT_QUESTION,
        )
        result = await self.db.execute(stmt)
        return result.scalars().first()

    @staticmethod
    def answer_of(row: OnboardingQuestion) -> str:
        """What the student answered, whichever shape the row is in.

        No index means the free-text row, whose answer is the whole of
        `option_a`; otherwise it is the option the index points at. One rule, so
        a reader of the onboarding never has to know where a question came from.
        """
        if row.selected_option_index is None:
            return row.option_a
        options = [row.option_a, row.option_b, row.option_c, row.option_d]
        return options[row.selected_option_index]

    @staticmethod
    def _row(
        goal_id: uuid.UUID,
        question: str,
        answer: str,
        index: int | None,
        ai_model: str,
        seconds: int | None,
    ) -> OnboardingQuestion:
        return OnboardingQuestion(
            goal_id=goal_id,
            question=question,
            option_a=answer,
            option_b="",
            option_c="",
            option_d="",
            selected_option_index=index,
            ai_model=ai_model,
            total_seconds=seconds,
        )


def _standard_row(goal_id: uuid.UUID, answer: StandardAnswer) -> OnboardingQuestion:
    """A standard question's row: all four options, and the one picked."""
    return OnboardingQuestion(
        goal_id=goal_id,
        question=answer.question,
        option_a=answer.options[0],
        option_b=answer.options[1],
        option_c=answer.options[2],
        option_d=answer.options[3],
        selected_option_index=answer.picked,
        ai_model=SYSTEM_AUTHOR,
        total_seconds=answer.seconds,
    )
