//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openapi/api.dart';
import 'package:test/test.dart';


/// tests for OnboardingApi
void main() {
  // final instance = OnboardingApi();

  group('tests for OnboardingApi', () {
    // Generate Follow Up Questions
    //
    // Initiate the onboarding process by analyzing the user's goal prompt and generating follow-up questions.
    //
    //Future<GoalCreationFollowUpQuestionsResponse> generateFollowUpQuestionsApiV1OnboardingFollowUpQuestionsPost(GoalCreationFollowUpQuestionsRequest goalCreationFollowUpQuestionsRequest) async
    test('test generateFollowUpQuestionsApiV1OnboardingFollowUpQuestionsPost', () async {
      // TODO
    });

    // Generate Full Creation
    //
    // Create user account and complete onboarding with goal and objective.
    //
    //Future<TokenResponse> generateFullCreationApiV1OnboardingFullCreationPost(GoalFullCreationRequest goalFullCreationRequest) async
    test('test generateFullCreationApiV1OnboardingFullCreationPost', () async {
      // TODO
    });

    // Generate Study Plan
    //
    // Receive the Study Plan generated by the AI.
    //
    //Future<GoalStudyPlanResponse> generateStudyPlanApiV1OnboardingStudyPlanPost(GoalStudyPlanRequest goalStudyPlanRequest) async
    test('test generateStudyPlanApiV1OnboardingStudyPlanPost', () async {
      // TODO
    });

  });
}
