from pydantic import BaseModel, Field

class OllamaStudentContext(BaseModel):
    """Schema for student context generated by Ollama"""
    state: str = Field(..., description="The student's current state/knowledge level")
    metacognition: str = Field(..., description="The student's metacognitive understanding and reasoning")

class OllamaStudentContextResponse(BaseModel):
    """Response wrapper for student context with AI model information"""
    state: str
    metacognition: str
    ai_model: str