"""initial schema

The whole schema as it stands on 2026-09-26, and the point at which it stops
being rebuilt from the models on every backend start (#157). Autogenerated from
`backend/models/`, then four things by hand:

- `CREATE EXTENSION vector` first, because seven columns are `Vector` and none
  of them can be created before the extension exists.
- `students.current_goal_id` gets its foreign key after `goals` exists.
  `students` and `goals` reference each other, so whichever table is created
  first cannot name the other yet - `use_alter=True` on the model is exactly
  this, and in a migration it is an `ALTER TABLE` of our own.
- `downgrade` drops the `studyresourcetype` enum. `create_table` created it,
  `drop_table` leaves it, and the next `upgrade` then fails on a type that
  already exists - so `downgrade base` followed by `upgrade head`, which is how
  a local database is reset now, would only work once.
- The `public` schema grants the old startup path ran are not here. They existed
  because it dropped the schema out from under itself and had to hand the
  recreated one back; nothing is dropped now.

Revision ID: a3d8362bfdd8
Revises:
Create Date: 2026-09-26 03:32:36.204547

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3d8362bfdd8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Before any table: every embedding column below is a pgvector type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("google_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_goal_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_id"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("description_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # The other half of the students <-> goals pair, now that goals exists.
    op.create_foreign_key(
        "students_current_goal_id_fkey",
        "students",
        "goals",
        ["current_goal_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True)
    op.create_table(
        "student_contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("state_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("metacognition", sa.String(), nullable=False),
        sa.Column("metacognition_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("is_still_valid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_student_context_student", "student_contexts", ["student_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("prompt_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("tutor_responses", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tutor_response_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("is_liked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_message_goal_created", "chat_messages", ["goal_id", "created_at"], unique=False
    )
    op.create_table(
        "frontiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("definition", sa.String(), nullable=False),
        sa.Column("definition_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_frontier_goal_id", "frontiers", ["goal_id"], unique=False)
    op.create_table(
        "onboarding_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("option_a", sa.String(), nullable=False),
        sa.Column("option_b", sa.String(), nullable=False),
        sa.Column("option_c", sa.String(), nullable=False),
        sa.Column("option_d", sa.String(), nullable=False),
        sa.Column("ai_model", sa.String(), nullable=False),
        sa.Column("selected_option_index", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "selected_option_index >= 0 AND selected_option_index <= 3",
            name="check_selected_option_index_range_onboarding",
        ),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_onboarding_question_goal_id", "onboarding_questions", ["goal_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("text_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.Column("option_a", sa.String(), nullable=False),
        sa.Column("option_b", sa.String(), nullable=False),
        sa.Column("option_c", sa.String(), nullable=False),
        sa.Column("option_d", sa.String(), nullable=False),
        sa.Column("right_answer_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "right_answer_index >= 0 AND right_answer_index <= 3",
            name="check_right_answer_index_range",
        ),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_question_goal_id", "questions", ["goal_id"], unique=False)
    op.create_table(
        "resources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum("pdf", "webpage", "youtube", name="studyresourcetype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description_embedding", pgvector.sqlalchemy.Vector(dim=3072), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_resource_goal_id", "resources", ["goal_id"], unique=False)
    op.create_table(
        "student_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("selected_index", sa.Integer(), nullable=False),
        sa.Column("total_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "selected_index >= 0 AND selected_index <= 3", name="check_selected_index_range"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_student_answer_lesson_id", "student_answers", ["lesson_id"], unique=False)
    op.create_index(
        "idx_student_answer_question_id_created_at",
        "student_answers",
        ["question_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_student_answer_question_id_created_at", table_name="student_answers")
    op.drop_index("idx_student_answer_lesson_id", table_name="student_answers")
    op.drop_table("student_answers")
    op.drop_index("idx_resource_goal_id", table_name="resources")
    op.drop_table("resources")
    # create_table made this enum type; dropping the table does not drop it,
    # and a second upgrade then fails on "type already exists".
    op.execute("DROP TYPE IF EXISTS studyresourcetype")
    op.drop_index("idx_question_goal_id", table_name="questions")
    op.drop_table("questions")
    op.drop_index("idx_onboarding_question_goal_id", table_name="onboarding_questions")
    op.drop_table("onboarding_questions")
    op.drop_index("idx_frontier_goal_id", table_name="frontiers")
    op.drop_table("frontiers")
    op.drop_index("idx_chat_message_goal_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("idx_student_context_student", table_name="student_contexts")
    op.drop_table("student_contexts")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_constraint("students_current_goal_id_fkey", "students", type_="foreignkey")
    op.drop_table("goals")
    op.drop_table("students")
    # ### end Alembic commands ###
    # The vector extension stays: it is the database's, not this schema's, and
    # dropping it would take any other schema's vector columns with it.
