"""initial migration

Revision ID: cb90c4636986
Revises: 
Create Date: 2026-01-14 23:50:57.693048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'cb90c4636986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Create students table first (without foreign keys) to break circular dependency
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('goal_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('current_objective_id', sa.UUID(), nullable=True),
    sa.Column('current_objective_name', sa.String(), nullable=True),
    sa.Column('overall_xp', sa.Integer(), nullable=False),
    sa.CheckConstraint('current_streak >= 0', name='check_current_streak_non_negative'),
    sa.CheckConstraint('longest_streak >= 0', name='check_longest_streak_non_negative'),
    sa.CheckConstraint('overall_xp >= 0', name='check_overall_xp_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('percentage_completed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.CheckConstraint('percentage_completed >= 0 AND percentage_completed <= 100', name='check_percentage_completed_range'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_objective_goal_id', 'objectives', ['goal_id'], unique=False)
    # Now add foreign key constraints to students table after goals and objectives exist
    op.create_foreign_key('fk_students_current_objective_id', 'students', 'objectives', ['current_objective_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_students_goal_id', 'students', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_student_current_objective_id', 'students', ['current_objective_id'], unique=False)
    op.create_index('idx_student_goal_id', 'students', ['goal_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('array_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_message_student_created', 'chat_messages', ['student_id', 'created_at'], unique=False)
    op.create_table('multiple_choice_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_answer_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.CheckConstraint('correct_answer_index >= 0 AND correct_answer_index <= 3', name='check_correct_answer_index_range'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcq_objective_id', 'multiple_choice_questions', ['objective_id'], unique=False)
    op.create_table('objective_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('info_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_objective_note_objective_id', 'objective_notes', ['objective_id'], unique=False)
    op.create_table('player_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('is_student_achievement', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'achievement_id', 'goal_id', name='uq_student_achievement_goal')
    )
    op.create_index('idx_player_achievement_achievement_id', 'player_achievements', ['achievement_id'], unique=False)
    op.create_index('idx_player_achievement_goal_id', 'player_achievements', ['goal_id'], unique=False)
    op.create_index('idx_player_achievement_student_id', 'player_achievements', ['student_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.Enum('pdf', 'webpage', 'youtube', name='studyresourcetype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index('idx_resource_goal_id', 'resources', ['goal_id'], unique=False)
    op.create_index('idx_resource_objective_id', 'resources', ['objective_id'], unique=False)
    op.create_table('streak_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_streak_day_student_date', 'streak_days', ['student_id', 'date_time'], unique=False)
    op.create_table('student_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_still_valid', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('state_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('metacognition', sa.String(), nullable=False),
    sa.Column('metacognition_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_context_goal_id', 'student_contexts', ['goal_id'], unique=False)
    op.create_index('idx_student_context_objective_id', 'student_contexts', ['objective_id'], unique=False)
    op.create_index('idx_student_context_student_id', 'student_contexts', ['student_id'], unique=False)
    op.create_table('subjective_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sq_objective_id', 'subjective_questions', ['objective_id'], unique=False)
    op.create_table('multiple_choice_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_answer_index', sa.Integer(), nullable=False),
    sa.Column('seconds_spent', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('student_answer_index >= 0 AND student_answer_index <= 3', name='check_student_answer_index_range'),
    sa.ForeignKeyConstraint(['question_id'], ['multiple_choice_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mca_question_id', 'multiple_choice_answers', ['question_id'], unique=False)
    op.create_index('idx_mca_student_id', 'multiple_choice_answers', ['student_id'], unique=False)
    op.create_table('subjective_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('student_answer', sa.String(), nullable=False),
    sa.Column('llm_approval', sa.Boolean(), nullable=True),
    sa.Column('llm_evaluation', sa.String(), nullable=True),
    sa.Column('llm_evaluation_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('llm_metacognition', sa.String(), nullable=True),
    sa.Column('llm_metacognition_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('seconds_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['subjective_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sa_question_id', 'subjective_answers', ['question_id'], unique=False)
    op.create_index('idx_sa_student_id', 'subjective_answers', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sa_student_id', table_name='subjective_answers')
    op.drop_index('idx_sa_question_id', table_name='subjective_answers')
    op.drop_table('subjective_answers')
    op.drop_index('idx_mca_student_id', table_name='multiple_choice_answers')
    op.drop_index('idx_mca_question_id', table_name='multiple_choice_answers')
    op.drop_table('multiple_choice_answers')
    op.drop_index('idx_sq_objective_id', table_name='subjective_questions')
    op.drop_table('subjective_questions')
    op.drop_index('idx_student_context_student_id', table_name='student_contexts')
    op.drop_index('idx_student_context_objective_id', table_name='student_contexts')
    op.drop_index('idx_student_context_goal_id', table_name='student_contexts')
    op.drop_table('student_contexts')
    op.drop_index('idx_streak_day_student_date', table_name='streak_days')
    op.drop_table('streak_days')
    op.drop_index('idx_resource_objective_id', table_name='resources')
    op.drop_index('idx_resource_goal_id', table_name='resources')
    op.drop_table('resources')
    op.drop_index('idx_player_achievement_student_id', table_name='player_achievements')
    op.drop_index('idx_player_achievement_goal_id', table_name='player_achievements')
    op.drop_index('idx_player_achievement_achievement_id', table_name='player_achievements')
    op.drop_table('player_achievements')
    op.drop_index('idx_objective_note_objective_id', table_name='objective_notes')
    op.drop_table('objective_notes')
    op.drop_index('idx_mcq_objective_id', table_name='multiple_choice_questions')
    op.drop_table('multiple_choice_questions')
    op.drop_index('idx_chat_message_student_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # Drop foreign keys from students table before dropping referenced tables
    op.drop_index('idx_student_goal_id', table_name='students')
    op.drop_index('idx_student_current_objective_id', table_name='students')
    op.drop_constraint('fk_students_goal_id', 'students', type_='foreignkey')
    op.drop_constraint('fk_students_current_objective_id', 'students', type_='foreignkey')
    op.drop_table('students')
    op.drop_index('idx_objective_goal_id', table_name='objectives')
    op.drop_table('objectives')
    op.drop_table('goals')
    op.drop_table('achievements')
    # ### end Alembic commands ###
