name: Build and Test

on:
  pull_request:
    types: [ready_for_review, opened]
    branches: [ main ]

# Add permissions for the workflow to modify PRs
permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run pytest
      run: |
        pytest tests/ -v
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        
    - name: Get dependencies
      run: |
        cd frontend
        flutter pub get
        flutter analyze
        flutter build apk --debug
        flutter build web
