from pydantic import BaseModel, Field

class GeminiStudentContext(BaseModel):
    """Schema for student context generated by Gemini"""
    state: str = Field(..., description="The student's current state/knowledge level")
    metacognition: str = Field(..., description="The student's metacognitive understanding and reasoning")
