from pydantic import BaseModel, Field


class StudentGoal(BaseModel):
    """One of the student's goals as a prompt sees it. The context generator
    reads all of them (#87): the reading is of the person, and a person who
    studies law and history is one learner, not two."""

    name: str
    description: str


class GeminiStudentContext(BaseModel):
    """Schema for student context generated by Gemini.

    It is also the shape a reader sends back into a prompt: what the model wrote
    about the student is exactly what lesson generation reads (#87)."""

    state: str = Field(..., description="The student's current state/knowledge level")
    metacognition: str = Field(
        ..., description="The student's metacognitive understanding and reasoning"
    )


class GeminiStudentContextResponse(BaseModel):
    """Response wrapper for student context with AI model information"""

    state: str
    metacognition: str
    ai_model: str
